- name: testing variable precedence
  hosts: mongodb
  # vars:
  #   NAME: sivakumar-play
     # vars_files: - line 5
  # - variables.yaml - line 6
  # vars_prompt:
  #   - name: NAME
  #     prompt: Please enter Trainer name
  #     private: false
  tasks:
  - name: variable at task level
    ansible.builtin.debug: 
      msg: "Trainer name is: {{NAME}}" 
      
# 1. comman line variables        
# 2. task level
# 3. vars_files
# 4. prompt
# 5. play
# 6. inventory
#7. roles








