- name: install package
  hosts: mongod
  become: yes
  tasks: 
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postman
    - cyrus-sasl-plain
    - mailx


